# -*- coding: utf-8 -*-
"""Test 2 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-sc-lOZHn1PCV3lfmqaNzjX9ZvzD5ke7
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/archive.zip")

df.head()

df.tail()

df.info()

df.describe().T

df.isnull().sum()

df.drop(["Diabetes"],axis=1)
df.info()

df.isnull().sum()/len(df)

from datetime import date
current_year=date.today().year
df['kg']=current_year-df["Weight"]
df.head()

print(df.Height.unique())
print(df.Weight.unique())

df.nunique()

cat_cols=df.select_dtypes(include=['object']).columns
num_cols=df.select_dtypes(include=np.number).columns.tolist()
print("categorical variable():")
print(cat_cols)
print("numerical variable():")
print(num_cols)

df['Heart Rate'] = df['Heart Rate'].astype(str)
df['Gender'] = df['Heart Rate'].str.split().str.get(0)
print(df[['Heart Rate', 'Gender', 'Temperature']])

df=pd.read_csv("/content/archive.zip")
print(df)

df1=df.dropna()
print(df1)

df2=df.dropna(axis=1)
print(df2)

df3=df.fillna(df.mean())
print(df3)

import pandas as pd
df=pd.read_csv("/content/archive.zip")
z_scores=(df-df.mean())/df.std()
outliers=df[abs(z_scores)>3]
print("univariate outliers:", outliers)

from google.colab import drive
drive.mount('/content/drive')